version: "3"

volumes:
  ledgers-app-ledgers-data:

services:

  ledgers-app-ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_app_ledgers_db
    restart: on-failure
    volumes:
    - ledgers-app-ledgers-data:/var/lib/pgsql/data
    expose:
    - 5432
    ports:
    - "5432:5432"    
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=ledgers
    - POSTGRESQL_USER=ledgers
    - POSTGRESQL_PASSWORD=ledgers

 