---
# develop branch
# yamllint disable rule:line-length
# ------------------------------------------------------------------
# Global settings
image: "adorsys/ci-build:latest"

# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Lint"
  - "Compile"      # build jar and provide as artifact
  - "Test"         # run tests and code quality checks
  - "Package"      # dockerize jar and push to docker registry
  - "Deploy"       # push to openshift registry (snapshot Deployment) or release registry
  - "Release"      # release

# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables: &variables


  ############################
  # Private Openshift Images #
  ############################

  DOCKER_IMAGE_NAME_LEDGERS: "ledgers"
  DOCKER_IMAGE_NAME_LEDGERS_KEYCLOAK: "ledgers-keycloak"
  DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN: "keycloak-and-ledgers-plugin"
  DOCKERHUB_NAMESPACE: "adorsys"

  ############################
  # Private Openshift ENV #
  ############################

  OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_DEV: "adorsys-modelbank-dev"
  OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_E2E: "adorsys-modelbank-e2e"

  ###########################
  # Build variables         #
  ###########################

  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

# Build Java
.build_java: &build_java
  stage: "Compile"
  script:
    - jabba use $BUILD_JAVA_VERSION
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -DskipTests clean install -Dci.build.number=Build\:${CI_PIPELINE_ID}
  # cache:
  #   key: "Java_${CI_COMMIT_REF_SLUG}"
  #   paths:
  #     - /builds/adorsys/xs2a/psd2-dynamic-sandbox/.m2/repository

# Build docker images and put them to DOCKER HUB repo
.build_dockerhub_image: &build_dockerhub_image
  script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
    - docker build -t "adorsys/ledgers:$DOCKER_TAG" .
    - docker build -t "adorsys/ledgers-keycloak:$DOCKER_TAG" keycloak
    - docker push "adorsys/ledgers:$DOCKER_TAG"
    - docker push "adorsys/ledgers-keycloak:$DOCKER_TAG"
    - docker logout

.push_dockerhub_images_private: &push_dockerhub_images_private
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_LEDGERS}:${DOCKER_TAG}" .
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN}:${DOCKER_TAG}" keycloak
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_LEDGERS}:${DOCKER_TAG}"
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN}:${DOCKER_TAG}"
    - docker logout

# Push docker images from dockehub to openshift
.push_docker_openshift: &push_docker_openshift
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_LEDGERS}:${DOCKER_TAG}"
    - docker login -u openshift -p $OPENSHIFT_TOKEN $OPENSHIFT_REGISTRY
    - docker tag "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_LEDGERS}:${DOCKER_TAG}" "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/${DOCKER_IMAGE_NAME_LEDGERS}:latest"
    - docker push "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/ledgers:latest"

.push_docker_keycloak_with_ledgers_plugin: &push_docker_keycloak_with_ledgers_plugin
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN}:${DOCKER_TAG}"
    - docker login -u openshift -p $OPENSHIFT_TOKEN $OPENSHIFT_REGISTRY
    - docker tag "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN}:${DOCKER_TAG}" "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/${DOCKER_IMAGE_NAME_KEYCLOAK_AND_LEDGERS_PLUGIN}:latest"
    - docker push "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/ledgers-keycloak:latest"

# release java artifact privately
.release_java_private: &release_java_private
  stage: "Release"
  script:
    - jabba use $BUILD_JAVA_VERSION
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp --settings scripts/mvn-release-settings.xml -Pgitlab-maven -DskipTests -U deploy

# ------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------

#-------------------------------------------------------------------
# lint
#-------------------------------------------------------------------

Lint:Docker_compose:
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt update && apt install yamllint docker-compose make -yq
    - echo "Run Docker compose lint"
    - docker-compose -f docker-compose.yml config  -q

Lint:Ci_file:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install yamllint python3-pkg-resources -yq
    - echo "Run Gitlab ci file lint"
    - yamllint -d relaxed .gitlab-ci.yml

Lint:Ledgers_yaml_json_xml:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install jsonlint yamllint libxml2-utils make curl -yq && ln -s /usr/bin/jsonlint-php /usr/bin/jsonlint
    - echo "Run Ledgers backend lint"
    - find ./ -type f -name "*.json" -exec jsonlint -q {} \; # lint all json
  # commented cause get many small errors for yaml with spaces empty lines and etc
  #   - find ./ -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}}}" {} \;
  # commented cause get error Unsupported version '1.1'
  #     - find ./ -type f \( -iname "*.xml" ! -iname pom.xml \) -exec xmllint --noout {} \;

Lint:ledgers_dockerfiles:
  image: docker:20.10
  stage: "Lint"
  services:
    - docker:20.10-dind
  except:
    - schedules
    - develop
    - master
  script:
    - echo "Run ledgers dockerfile checks"
    - docker run --rm -i hadolint/hadolint < Dockerfile

Lint:PMD_CPD_Report:
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt update && apt install make -yq
    - echo "Test java code for PMD and CPD"
    - mvn -ntp -Dmaven.test.skip=true package pmd:check pmd:cpd-check
  cache: {}
  artifacts:
    paths:
      - "qa/pmd/pmd-ruleset.xml"
      - "**/**/*/pmd.html"
      - "**/*/pmd.xml"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"

#-------------------------------------------------------------------
# Compile
#-------------------------------------------------------------------

Build:Ledgers:
  stage: "Compile"
  except:
    - schedules
  <<: *build_java
  variables:
    BUILD_JAVA_VERSION: system@1.11
  artifacts:
    paths:
      - "ledgers-app/target/ledgers-app*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-repository/target/ledgers-deposit-account-repository*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-service-api/target/ledgers-deposit-account-service-api*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-service-impl/target/ledgers-deposit-account-service-impl*jar"
      - "ledgers-middleware/ledgers-middleware-rest-server/target/ledgers-middleware-rest-server*jar"
      - "ledgers-middleware/ledgers-middleware-service-api/target/ledgers-middleware-service-api*jar"
      - "ledgers-middleware/ledgers-middleware-service-impl/target/ledgers-middleware-service-impl*jar"
      - "ledgers-mockbank/ledgers-mockbank-simple/target/ledgers-mockbank-simple*jar"
      - "ledgers-mockbank/ledgers-mockbank-simple-data-test/target/ledgers-mockbank-simple-data-test*jar"
      - "ledgers-postings/ledgers-postings-repository/target/ledgers-postings-repository*jar"
      - "ledgers-postings/ledgers-postings-rest-server/target/ledgers-postings-rest-server*jar"
      - "ledgers-postings/ledgers-postings-service-api/target/ledgers-postings-service-api*jar"
      - "ledgers-postings/ledgers-postings-service-impl/target/ledgers-postings-service-impl*jar"
      - "ledgers-sca/ledgers-sca-repository/target/ledgers-sca-repository*jar"
      - "ledgers-sca/ledgers-sca-service-api/target/ledgers-sca-service-api*jar"
      - "ledgers-sca/ledgers-sca-service-impl/target/ledgers-sca-service-impl*jar"
      - "ledgers-user-management/ledgers-user-management-repository/target/ledgers-user-management-repository*jar"
      - "ledgers-user-management/ledgers-user-management-rest-server/target/ledgers-user-management-rest-server*jar"
      - "ledgers-user-management/ledgers-user-management-service-api/target/ledgers-user-management-service-api*jar"
      - "ledgers-user-management/ledgers-user-management-service-impl/target/ledgers-user-management-service-impl*jar"
      - "ledgers-utils/target/ledgers-utils*jar"
      - "keycloak/keycloak-token-exchange/target/keycloak-token-exchange*.jar"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}"
    expire_in: "1 day"

#-------------------------------------------------------------------
# Tests
#-------------------------------------------------------------------

Javadoc Check Java11:
  stage: "Test"
  except:
    - schedules
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -Dmaven.test.skip=true package javadoc:javadoc
  artifacts:
    paths:
      - "**/target/site/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-javadoc"
    expire_in: "10 day"

Unit Tests Java11:
  stage: "Test"
  except:
    - schedules
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --fail-at-end clean install
  artifacts:
    paths:
      - "**/target/surefire-reports/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-*"
    expire_in: "10 day"

###########
# develop branch #
###########

build_dockerhub_image_develop_private:
  stage: "Package"
  except:
    - schedules
  only:
    - develop
    - KOA_ledger_make_private
  variables:
    DOCKER_TAG: develop
    DOCKERHUB_REGISTRY: gitlab-registry.adorsys.de
    DOCKERHUB_NAMESPACE: "adorsys/xs2a/ledgers"
  <<: *push_dockerhub_images_private

Deploy Image to Openshift (adorsys-modelbank-dev):
  stage: Deploy
  except:
    - schedules
  only:
    - develop
    - KOA_ledger_make_private
  environment:
    name: dev
    url: ~
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_DEV}
  <<: *push_docker_openshift

Deploy Keycloak to Openshift (adorsys-modelbank-dev):
  stage: Deploy
  except:
    - schedules
  only:
    - develop
    - KOA_ledger_make_private
  environment:
    name: dev
    url: ~
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_DEV}
  <<: *push_docker_keycloak_with_ledgers_plugin

Deploy image to Openshift (adorsys-modelbank-e2e):
  stage: Deploy
  only:
    - schedules
  environment:
    name: dev
    url: ~
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_E2E}
  <<: *push_docker_openshift

Deploy Keycloak to Openshift (adorsys-modelbank-e2e):
  stage: Deploy
  only:
    - schedules
  environment:
    name: dev
    url: ~
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_ADORSYS_MODELBANK_E2E}
  <<: *push_docker_keycloak_with_ledgers_plugin

###########
# Release (tags) #
###########

Push to DockerHub (Release):
  stage: "Package"
  only:
    - tags
  variables:
    DOCKER_TAG: $CI_COMMIT_TAG
    DOCKERHUB_REGISTRY: gitlab-registry.adorsys.de
    DOCKERHUB_NAMESPACE: "adorsys/xs2a/ledgers"
  <<: *push_dockerhub_images_private

release_snapshot_artifacts_private:
  stage: "Release"
  except:
    - schedules
  cache: {}
  variables:
    BUILD_JAVA_VERSION: system@1.11
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  only:
    - develop
    - KOA_ledger_make_private
  <<: *release_java_private

release_artifacts_private:
  stage: "Release"
  except:
    - schedules
  cache: {}
  variables:
    BUILD_JAVA_VERSION: system@1.11
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  only:
    - tags
  <<: *release_java_private

##########
# master #
##########

Push to DockerHub (Master):
  stage: "Package"
  only:
    - master
  variables:
    DOCKER_TAG: latest
    DOCKERHUB_REGISTRY: gitlab-registry.adorsys.de
    DOCKERHUB_NAMESPACE: "adorsys/xs2a/ledgers"
  <<: *push_dockerhub_images_private
