# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Lint"
  - "Compile"      # build jar and provide as artifact
  - "Test"         # run tests and code quality checks
  - "Package"      # dockerize jar and push to docker registry
  - "Deployment"   # push to openshift registry (snapshot Deployment) or release registry

image: "adorsys/ci-build"

# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables: &variables

  ###########################
  # Docker images variables #
  ###########################

  OPENSHIFT_NAMESPACE_LEDGERS_DEV: "ledgers-dev"
  OPENSHIFT_NAMESPACE_SANDBOX_DEV: "adorsys-dynamic-sandbox-dev"
  OPENSHIFT_NAMESPACE_GATEWAY_DEV: "banking-gateway-dev"
  OPENSHIFT_NAMESPACE_DXC_SANDBOX_DEV: "dxc-sandbox-dev"
  OPENSHIFT_NAMESPACE_BEKB_SANDBOX_DEV: "bekb-sandbox-dev"
  OPENSHIFT_NAMESPACE_DEV_E2E: adorsys-dynamic-sandbox-dev-e2e

  SONAR_HOST: "https://psd2-quality.cloud.adorsys.de"

  ###########################
  # Build variables         #
  ###########################

  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

.build_dockerhub_image: &build_dockerhub_image
  script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
    - docker build -t "adorsys/ledgers:$DOCKER_TAG" .
    - docker push "adorsys/ledgers:$DOCKER_TAG"
    - docker logout

.push_docker_openshift: &push_docker_openshift
  script:
    - docker pull adorsys/ledgers:${DOCKER_TAG}
    - docker login -u openshift -p $OPENSHIFT_TOKEN $OPENSHIFT_REGISTRY
    - docker tag "adorsys/ledgers:${DOCKER_TAG}" "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/ledgers:latest" 
    - docker push "${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/ledgers:latest"

# ------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------

Compile:
  stage: "Compile"
  except:
    - schedules
  script:
    - mvn -DskipTests clean install -Dci.build.number=Build\:${CI_PIPELINE_ID}
  artifacts:
    paths:
      - "ledgers-app/target/ledgers-app*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-repository/target/ledgers-deposit-account-repository*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-service-api/target/ledgers-deposit-account-service-api*jar"
      - "ledgers-deposit-account/ledgers-deposit-account-service-impl/target/ledgers-deposit-account-service-impl*jar"
      - "ledgers-middleware/ledgers-middleware-rest-server/target/ledgers-middleware-rest-server*jar"
      - "ledgers-middleware/ledgers-middleware-service-api/target/ledgers-middleware-service-api*jar"
      - "ledgers-middleware/ledgers-middleware-service-impl/target/ledgers-middleware-service-impl*jar"
      - "ledgers-mockbank/ledgers-mockbank-simple/target/ledgers-mockbank-simple*jar"
      - "ledgers-mockbank/ledgers-mockbank-simple-data-test/target/ledgers-mockbank-simple-data-test*jar"
      - "ledgers-postings/ledgers-postings-repository/target/ledgers-postings-repository*jar"
      - "ledgers-postings/ledgers-postings-rest-server/target/ledgers-postings-rest-server*jar"
      - "ledgers-postings/ledgers-postings-service-api/target/ledgers-postings-service-api*jar"
      - "ledgers-postings/ledgers-postings-service-impl/target/ledgers-postings-service-impl*jar"
      - "ledgers-sca/ledgers-sca-repository/target/ledgers-sca-repository*jar"
      - "ledgers-sca/ledgers-sca-service-api/target/ledgers-sca-service-api*jar"
      - "ledgers-sca/ledgers-sca-service-impl/target/ledgers-sca-service-impl*jar"
      - "ledgers-user-management/ledgers-user-management-repository/target/ledgers-user-management-repository*jar"
      - "ledgers-user-management/ledgers-user-management-rest-server/target/ledgers-user-management-rest-server*jar"
      - "ledgers-user-management/ledgers-user-management-service-api/target/ledgers-user-management-service-api*jar"
      - "ledgers-user-management/ledgers-user-management-service-impl/target/ledgers-user-management-service-impl*jar"
      - "ledgers-utils/target/ledgers-utils*jar"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}"
    expire_in: "1 day"

PMD_CPD_Report:
  stage: "Lint"
  except:
    - schedules
    - develop
  script:
    - mvn -Dmaven.test.skip=true package pmd:pmd pmd:cpd
  artifacts:
    paths:
      - "qa/pmd/pmd-ruleset.xml"
      - "**/**/*/pmd.html"
      - "**/*/pmd.xml"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"

PMD_CPD_Check:
  stage: "Lint"
  except:
    - schedules
    - develop
  script:
    - mvn -Dmaven.test.skip=true package pmd:check pmd:cpd-check
  artifacts:
    paths:
      - "qa/pmd/pmd-ruleset.xml"
      - "**/**/*/pmd.html"
      - "**/*/pmd.xml"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"

Javadoc Check:
  stage: "Test"
  except:
    - schedules
  script:
    - mvn -Dmaven.test.skip=true package javadoc:javadoc
  artifacts:
    paths:
      - "**/target/site/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-javadoc"
    expire_in: "10 day"

Unit Tests:
  stage: "Test"
  except:
    - schedules
  script:
    - mvn --fail-at-end clean install
  artifacts:
    paths:
      - "**/target/surefire-reports/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-*"
    expire_in: "10 day"

###########
# develop #
###########

Sonarcube Tests:
  stage: "Test"
  needs: []
  except:
    - schedules
    - develop
  script:
    - jabba use system@1.8
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp --fail-at-end clean install
    - mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN}

Push to DockerHub (develop):
  stage: "Package"
  except:
    - schedules
  only:
    - develop
  variables:
    DOCKER_TAG: develop
  <<: *build_dockerhub_image

Deploy Openshift (ledgers-dev):
  stage: Deployment
  except:
    - schedules
  only:
    - develop
  environment:
    name: dev
    url: https://ledgers-dev.cloud.adorsys.de
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_LEDGERS_DEV}
  <<: *push_docker_openshift

Deploy Openshift (sandbox-dev):
  stage: Deployment
  except:
    - schedules
  only:
    - develop
  environment:
    name: dev
    url: https://dev-dynamicsandbox-ledgers.cloud.adorsys.de
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_SANDBOX_DEV}
  <<: *push_docker_openshift

#Deploy Openshift (gateway-dev):
#  stage: Deployment
#  only:
#    - develop
#  environment:
#    name: dev
#    url: https://dev-bankinggateway-sandbox-ledgers.cloud.adorsys.de
#  variables:
#    DOCKER_TAG: latest
#    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_GATEWAY_DEV}
#  <<: *push_docker_openshift

Deploy Openshift (dxc-sandbox-dev):
  stage: Deployment
  except:
    - schedules
  only:
    - develop
  environment:
    name: dxc-dev
    url: https://dxc-dev-dynamicsandbox-ledgers.cloud.adorsys.de
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_DXC_SANDBOX_DEV}
  <<: *push_docker_openshift

Deploy Openshift (bekb-sandbox-dev):
  stage: Deployment
  except:
    - schedules
  only:
    - develop
  environment:
    name: bekb-dev
    url: https://bekb-dev-dynamicsandbox-ledgers.cloud.adorsys.de
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_BEKB_SANDBOX_DEV}
  <<: *push_docker_openshift

Deploy Openshift (sandbox-dev-e2e):
  stage: Deployment
  except:
    - schedules
  only:
    - develop
  environment:
    name: dev-e2e
    url: https://dev-e2e-dynamicsandbox-ledgers.cloud.adorsys.de
  variables:
    DOCKER_TAG: develop
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_DEV_E2E}
  <<: *push_docker_openshift
  
##########
# master #
##########

Push to DockerHub (master):
  stage: "Package"
  only:
    - master
  variables:
    DOCKER_TAG: latest
  environment:
    name: demo
  <<: *build_dockerhub_image

#######
# tag #
#######

Push to DockerHub (release):
  stage: "Package"
  only:
    - tags
  variables:
    DOCKER_TAG: $CI_COMMIT_TAG
  <<: *build_dockerhub_image

