version: '3'

networks:
  ledgers-net:

volumes:
  ledgers-data:

services:

  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ledgers-net
    ports:
      - "8088:8088"
    depends_on:
      - ledgers-db
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=ledgers_db
<<<<<<< HEAD
      - SPRING_PROFILES_ACTIVE=postgres
=======
      - DB_DATABASE=ledgers
      - DB_USER=ledgers
      - DB_PASSWORD=ledgers

>>>>>>> develop

  ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
      - ledgers-data:/var/lib/pgsql/data
    expose:
      - 5432
    networks:
      - ledgers-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=ledgers
      - POSTGRESQL_USER=ledgers
      - POSTGRESQL_PASSWORD=ledgers
