version: '3'

networks:
  ledgers-net:

volumes:
  ledgers-data:
  keycloak-data:

services:
  ledgers-keycloak:
    image: gitlab-registry.adorsys.de/adorsys/xs2a/ledgers/keycloak-and-ledgers-plugin:${LEDGERS_VERSION}
    container_name: ledgers-keycloak
    restart: on-failure
    build:
      context: keycloak
      dockerfile: Dockerfile
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - ledgers-net
    ports:
    - "8080:8080"
    environment:
      - KC_HOSTNAME=ledgers-keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge

  ledgers:
    image: gitlab-registry.adorsys.de/adorsys/xs2a/ledgers/ledgers:${LEDGERS_VERSION}
    container_name: ledgers
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ledgers-net
    ports:
      - "8088:8088"
      - "8188:8001"
    depends_on:
      - ledgers-db
      - ledgers-keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,sandbox
      - SPRING_JPA_SHOW_SQL=false
      - KEYCLOAK_AUTH_SERVER_URL=http://ledgers-keycloak:8080
      - DB_HOST=ledgers_db
      - DB_DATABASE=ledgers
      - DB_USER=ledgers
      - DB_PASSWORD=ledgers
      - LIQUIBASE_ENABLED=true
      - LEDGERS_SCA_MULTILEVEL_ENABLED=true
      - LEDGERS_SCA_AUTHORISATION_CONFIRMATION_ENABLED=false
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=modelbank.mail@gmail.com
      - SPRING_MAIL_PASSWORD=password
      - SPRING_MAIL_PROPERTIES_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_SMTP_SSL=true
      - SPRING_MAIL_PROPERTIES_SMTP_START_TLS=false
      - SPRING_MAIL_PROPERTIES_SMTP_FROM=modelbank.mail@gmail.com
      - SPRING_MAIL_PROPERTIES_SMTP_FROM_DISPLAY_NAME=Ledgers
      - SPRING_MAIL_PROPERTIES_SMTP_ENVELOPE_FROM=modelbank.mail@gmail.com
      - SPRING_MAIL_PROPERTIES_SMTP_REPLY_TO=modelbank.mail@gmail.com
      - SPRING_MAIL_PROPERTIES_SMTP_REPLY_TO_DISPLAY_NAME=Ledgers support

  ledgers-db:
    image: centos/postgresql-12-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
      - ledgers-data:/var/lib/pgsql/data
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - ledgers-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=ledgers
      - POSTGRESQL_USER=ledgers
      - POSTGRESQL_PASSWORD=ledgers
