version: '3'

networks:
  ledgers-net:

volumes:
  ledgers-data:

services:
  ledgers-keycloak:
    image: adorsys/ledgres-keycloak
    container_name: ledgers-keycloak
    restart: on-failure
    build:
      context: keycloak
      dockerfile: Dockerfile
    networks:
      - ledgers-net
    ports:
    - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ledgers-net
    ports:
      - "8088:8088"
      - "8188:8001"
    depends_on:
      - ledgers-db
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,sandbox
      - SPRING_JPA_SHOW_SQL=false
      - KEYCLOAK_AUTH_SERVER_URL=http://ledgers-keycloak:8080
      - DB_HOST=ledgers_db
      - DB_DATABASE=ledgers
      - DB_USER=ledgers
      - DB_PASSWORD=ledgers
      - LIQUIBASE_ENABLED=true
      - LEDGERS_SCA_MULTILEVEL_ENABLED=false
      - LEDGERS_SCA_AUTHORISATION_CONFIRMATION_ENABLED=false

  ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
      - ledgers-data:/var/lib/pgsql/data
    expose:
      - 5432
    networks:
      - ledgers-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=ledgers
      - POSTGRESQL_USER=ledgers
      - POSTGRESQL_PASSWORD=ledgers
