apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: ledgers
  namespace: ledgers-dev
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8088
  selector:
    app: server
    deploymentconfig: ledgers
  sessionAffinity: None
  type: ClusterIP