apiVersion: v1
name: ledgers
version: 0.1.0
appVersion: "1.0"
description: Ledgers Helm charts
sources:
  - https://git.adorsys.de/adorsys/xs2a/ledgers
maintainers:
  - name: Serhii Petrychenko
    email: spe@adorsys.com.ua
