name: Develop CI

on: 
  push:
    branches:
      - KOA__install_github_actions    

jobs:
  build:
    name: Build Ledgers (openjdk 1.8)
    runs-on: ubuntu-latest
    steps:
      - name: Clone ledgers develop repository
        uses: actions/checkout@v2

      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2

      - name: Build Ledgers 
        run: mvn -DskipTests -Dmaven.javadoc.skip=true clean install

  # javaDoc:

  # pmdCheck:

  # test:

  # sonar:

  # deployMavenCentral:
