apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: server
  name: postgres
  namespace: ledgers-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: server
    deploymentconfig: postgres
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      labels:
        app: server
        deploymentconfig: postgres
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: ledgers
            - name: POSTGRESQL_PASSWORD
              value: ledgers
            - name: POSTGRESQL_USER
              value: ledgers
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: ledgers
          image: >-
            centos/postgresql-95-centos7@sha256:209e2b82e608241f2fee65a45d8fc4defe3b50509dc992c2de10532fe8d0ecb7
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-volume-1
          persistentVolumeClaim:
            claimName: db-data
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgres
        from:
          kind: ImageStreamTag
          name: 'postgresql-95-centos7:latest'
          namespace: ledgers-dev
      type: ImageChange
    - type: ConfigChange
