apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: postgres
  namespace: ledgers-dev
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: server
    deploymentconfig: postgres
  sessionAffinity: None
  type: ClusterIP
